name: integration

on:
  push:
    branches: [ dev, stable ]
  pull_request:
    branches: [ dev, stable ]
  schedule:
    - cron: '0 0 */16 * *'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2019 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up CMake 3.18
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: 3.18

      - name: Install GCC 11
        if: runner.os == 'Linux'
        run: |
          sudo apt install gcc-11 g++-11

      - name: Build with GCC 11
        if: runner.os != 'Windows'
        run: |
          cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -B build -S .
          cmake --build build --config $BUILD_TYPE
        working-directory: ./source/test/integration/fetch_content
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Build with Visual Studio
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE -B build -S .
          cmake --build build --config $BUILD_TYPE
        working-directory: ./source/test/integration/fetch_content

      - name: Run
        shell: bash
        run:
          ctest -V -C $BUILD_TYPE
        working-directory: ./source/test/integration/fetch_content/build
